# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEVNm8PHw5ldB1VtedeOaQJp2RW0dDuH
"""

from fastapi import FastAPI
import yfinance as yf

app = FastAPI()

@app.get("/aia-stock")
def get_aia_stock():
    ticker = yf.Ticker("1299.HK")
    info = ticker.info

    # Dados brutos
    current_price = info.get("currentPrice")
    market_cap = info.get("marketCap")
    shares_outstanding = info.get("sharesOutstanding")

    # Dados formatados
    formatted_price = f"HK${current_price:,.2f}" if current_price else "N/A"
    formatted_market_cap = f"HK${market_cap / 1e9:,.2f}B" if market_cap else "N/A"
    formatted_shares = f"{shares_outstanding / 1e9:,.2f}B" if shares_outstanding else "N/A"

    return {
        "current_price": formatted_price,
        "market_cap": formatted_market_cap,
        "shares_outstanding": formatted_shares
        }